name: Collect Library Licenses

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

permissions: {} # No permissions by default on workflow level

jobs:
  collect-licenses:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Collect library licenses
        uses: open-edge-platform/geti-ci/actions/collect-sbom-library@4d46c7fb444d8fae6390348e76d96bb0749c5632
        with:
          path: .
